# Generated by Django 5.1.4 on 2025-03-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
