# Generated by Django 5.1.4 on 2025-03-05 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_app', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='product_image')),
                ('image2', models.ImageField(upload_to='product_image')),
                ('image3', models.ImageField(upload_to='product_image')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clock_app.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clock_app.category')),
            ],
        ),
    ]
